name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.11.x', '1.12.x', '1.13.x' ]
    name: Go ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Test
      run: go test ./... -v -mod=vendor -race -count=1 -coverprofile=coverage.txt -covermode=atomic -timeout=120s
